# docker-compose.yml
version: "3.8"
services:
  web:
    build: .
    ports:
      - "5002:5000"
    environment:
      - FLASK_ENV=development
      - DATABASE_URL=postgresql://username:password@db/database_name
    depends_on:
      - db
  db:
    image: postgres:13
    environment:
      - POSTGRES_USER=username
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=database_name
    ports:
      - "5432:5432"
